---
- name: send CA script
  template:
    src: CA.j2
    dest: /etc/pki/tls/misc/CA
    owner: root
    group: root
    mode: 755

- name: send openssl.conf
  template:
    src: openssl.cnf.j2
    dest: /etc/pki/tls/openssl.cnf
    owner: root
    group: root
    mode: 644

- name: check whether or not CA exists
  stat:
    path: /etc/pki/CA/private/cakey.pem
  register: ret_check_ca

- name: install CA
  shell: /etc/pki/tls/misc/CA -newca
  when: ret_check_ca.stat.exists == false

