---
- name: update package list
  raw: apt-get update
  changed_when: false

- name: check python is installed
  raw: dpkg -l python
  changed_when: false
  failed_when: false
  register: ret_check_python

- name: install python
  raw: apt-get install -y python
  changed_when: ret_install_python.rc == 0
  when: ret_check_python.rc != 0
  register: ret_install_python

- name: install japanese packages
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - language-pack-ja-base
    - language-pack-ja

- name: add setting locale in .profile
  lineinfile:
    dest: /root/.profile
    line: export LANG={{ docker_japanese.locale }}
    state: present

