---
- name: Create_Domain(check)
  shell: openstack domain show {{ openstack_keystone_setup.domain }}
  environment:
    OS_TOKEN: "{{ openstack_keystone_setup.admin_token  }}"
    OS_URL: http://{{ openstack_keystone_setup.controller }}:35357/v3
    OS_IDENTITY_API_VERSION: 3
  changed_when: false
  failed_when: false
  register: ret_check_domain

- name: Create_Domain(create)
  shell: openstack domain create {{ openstack_keystone_setup.domain }}
  environment:
    OS_TOKEN: "{{ openstack_keystone_setup.admin_token  }}"
    OS_URL: http://{{ openstack_keystone_setup.controller }}:35357/v3
    OS_IDENTITY_API_VERSION: 3
  when: ret_check_domain.rc != 0

