---
- name: Create_Demo_User(check)
  shell: openstack user show demo
  environment:
    OS_TOKEN: "{{ openstack_keystone_setup.admin_token  }}"
    OS_URL: http://{{ openstack_keystone_setup.controller }}:35357/v3
    OS_IDENTITY_API_VERSION: 3
  changed_when: false
  failed_when: false
  register: ret_check_demo_user

- name: Create_Demo_User(create)
  shell: openstack user create --domain {{ openstack_keystone_setup.domain }} demo --password {{ openstack_keystone_setup.demo_pass }}
  environment:
    OS_TOKEN: "{{ openstack_keystone_setup.admin_token  }}"
    OS_URL: http://{{ openstack_keystone_setup.controller }}:35357/v3
    OS_IDENTITY_API_VERSION: 3
  when: ret_check_demo_user.rc != 0

