---
- name: Create_Admin_Project(check)
  shell: openstack project show admin
  environment:
    OS_TOKEN: "{{ openstack_keystone_setup.admin_token  }}"
    OS_URL: http://{{ openstack_keystone_setup.controller }}:35357/v3
    OS_IDENTITY_API_VERSION: 3
  changed_when: false
  failed_when: false
  register: ret_check_admin_project

- name: Create_Admin_Project(create)
  shell: openstack project create --domain {{ openstack_keystone_setup.domain }} admin
  environment:
    OS_TOKEN: "{{ openstack_keystone_setup.admin_token  }}"
    OS_URL: http://{{ openstack_keystone_setup.controller }}:35357/v3
    OS_IDENTITY_API_VERSION: 3
  when: ret_check_admin_project.rc != 0

