---
- name: Setting_Chrony(delete_server_entry)
  lineinfile: >
    dest=/etc/chrony.conf
    regexp="^server\s.\.centos\.pool\.ntp\.org\siburst"
    state=absent
  notify: restart service

- name: Setting_Chrony(add_server_entry_for_controller)
  lineinfile:
    dest=/etc/chrony.conf
    line="server {{ item }} iburst"
    state=present
    insertafter="# Please consider joining the pool"
  with_items: >
    openstack_ntp.controller_ntp_entry
  when: >
    ansible_hostname == openstack_ntp.controller
  notify: restart service

- name: Setting_Chrony(add_server_entry_for_others)
  lineinfile:
    dest=/etc/chrony.conf
    line="server {{ openstack_ntp.controller }} iburst"
    state=present
    insertafter="# Please consider joining the pool"
  when: >
    ansible_hostname != openstack_ntp.controller
  notify: restart service

- name: Setting_Chrony(add_allow_ip_for_controller)
  lineinfile:
    dest=/etc/chrony.conf
    line="allow {{ item }}"
    state=present
    insertafter="# Allow NTP client access from local network"
  with_items:
    openstack_ntp.controller_allow_network
  when: >
    ansible_hostname == openstack_ntp.controller
  notify: restart service

