---
- name: create minidlna container
  hosts: 192.168.0.50
  tasks:
    - name: create container
      docker_container:
        name: tst-vir-dlna01
        image: "docker.io/ubuntu:16.04"
        command: /bin/bash
        exposed_ports:
          - "8200:8200/tcp"
          - "1900:1900/udp"
        network_mode: host
        state: started
        tty: yes
        interactive: yes
        detach: yes

    - name: add container
      add_host:
        name: tst-vir-dlna01

- name: configure minidlna container
  hosts: tst-vir-dlna01
  connection: docker
  gather_facts: no
  tasks: 
    - name: install python
      raw: apt-get update && apt-get install -y python
      register: ret_python
      changed_when: 
        ret_python.rc == 0
    - name: install minidlna
      apt:
        name=minidlna
        state=present
    - name: start minidlna
      service:
        name: minidlna
        state: started

#- name: save minidlna container
#  hosts: 192.168.0.50
#  tasks:
#    - name: check minidlna image
#      shell: 'docker images | grep "minidlna\s\+0.1"'
#      changed_when: false
#      failed_when: false
#      register: ret_check

#    - name: remove minidlna image
#      shell: docker rmi minidlna:0.1
#      when: ret_check.rc == 0

#    - name: save minidlna container
#      shell: 'docker commit -c "CMD service minidlna start && /bin/bash" tst-vir-dlna01 minidlna:0.1'

#    - name: absent container
#      docker_container:
#        name: tst-vir-dlna01
#        state: absent
