---
- name: Create_Service(check)
  shell: . {{ openstack_neutron_controller.script_dir }}/admin-openrc && openstack service show neutron
  register: ret_check
  failed_when: false
  changed_when: false

- name: Create_Service(create)
  shell: . {{ openstack_neutron_controller.script_dir }}/admin-openrc && openstack service create --name neutron --description "OpenStack Networking" network
  when: ret_check.rc != 0

