---
- name: Create_User(check_exist)
  shell: . {{ openstack_neutron_controller.script_dir }}/admin-openrc && openstack user show neutron
  failed_when: false
  changed_when: false
  register: ret_check_exist

- name: Create_User(create_user)
  shell: . {{ openstack_neutron_controller.script_dir }}/admin-openrc && openstack user create --domain {{ openstack_neutron_controller.domain }} --password {{ openstack_neutron_controller.neutron_pass }} neutron
  when: ret_check_exist.rc != 0

- name: Create_User(check_role)
  shell: . {{ openstack_neutron_controller.script_dir }}/admin-openrc && openstack role list --user neutron --project service | grep admin
  changed_when: false
  failed_when: false
  register: ret_check_role

- name: Add_Role_Admin_User(create)
  shell: . {{ openstack_neutron_controller.script_dir }}/admin-openrc && openstack role add --project service --user neutron admin
  when: ret_check_role.rc != 0

