---
- name: Create_Database(check_database_neutron)
  shell: mysql -uroot -p{{ openstack_neutron_controller.mariadb_pass }} -e "show databases;" | grep neutron
  register: ret_check_database_neutron
  changed_when: false
  failed_when: false

- name: Create_Database(create_database_neutron)
  shell: mysql -uroot -p{{ openstack_neutron_controller.mariadb_pass }} -e "CREATE DATABASE neutron;"
  when: ret_check_database_neutron.rc != 0

- name: Create_Database(neutron_check_grant01)
  shell: mysql -uroot -p{{ openstack_neutron_controller.mariadb_pass }} -e "show grants for 'neutron'@'localhost'" | grep "ALL PRIVILEGES ON \`neutron\`\.\* TO 'neutron'@'localhost'"
  register: ret_neutron_check_grant01
  changed_when: false
  failed_when: false

- name: Create_Database(neutron_grant01)
  shell: mysql -uroot -p{{ openstack_neutron_controller.mariadb_pass }} -e "GRANT ALL PRIVILEGES ON neutron.* TO 'neutron'@'localhost' IDENTIFIED BY '{{ openstack_neutron_controller.neutron_dbpass }}';"
  when: ret_neutron_check_grant01.rc != 0

- name: Create_Database(neutron_check_grant02)
  shell: mysql -uroot -p{{ openstack_neutron_controller.mariadb_pass }} -e "show grants for 'neutron'@'%'" | grep "ALL PRIVILEGES ON \`neutron\`\.\* TO 'neutron'@'%'"
  register: ret_neutron_check_grant02
  changed_when: false
  failed_when: false

- name: Create_Database(neutron_grant02)
  shell: mysql -uroot -p{{ openstack_neutron_controller.mariadb_pass }} -e "GRANT ALL PRIVILEGES ON neutron.* TO 'neutron'@'%' IDENTIFIED BY '{{ openstack_neutron_controller.neutron_dbpass }}';"
  when: ret_neutron_check_grant02.rc != 0

