---
- name: Create_Endpoint(check01)
  shell: . {{ openstack_neutron_controller.script_dir }}/admin-openrc && openstack endpoint list | grep neutron | grep public
  register: ret_check01
  failed_when: false
  changed_when: false

- name: Create_Endpoint(create01)
  shell: . {{ openstack_neutron_controller.script_dir }}/admin-openrc && openstack endpoint create --region {{ openstack_neutron_controller.region }} network public http://{{ openstack_neutron_controller.controller }}:9696
  when: ret_check01.rc != 0

- name: Create_Endpoint(check02)
  shell: . {{ openstack_neutron_controller.script_dir }}/admin-openrc && openstack endpoint list | grep neutron | grep internal
  register: ret_check02
  failed_when: false
  changed_when: false

- name: Create_Endpoint(create02)
  shell: . {{ openstack_neutron_controller.script_dir }}/admin-openrc && openstack endpoint create --region {{ openstack_neutron_controller.region }} network internal http://{{ openstack_neutron_controller.controller }}:9696
  when: ret_check02.rc != 0

- name: Create_Endpoint(check03)
  shell: . {{ openstack_neutron_controller.script_dir }}/admin-openrc && openstack endpoint list | grep neutron | grep admin
  register: ret_check03
  failed_when: false
  changed_when: false

- name: Create_Endpoint(create03)
  shell: . {{ openstack_neutron_controller.script_dir }}/admin-openrc &&  openstack endpoint create --region {{ openstack_neutron_controller.region }} network admin http://{{ openstack_neutron_controller.controller }}:9696
  when: ret_check03.rc != 0

