---
- include: Create_Keydir.yml
- include: Create_Database.yml
- include: Create_User.yml
- include: Create_Service.yml
- include: Create_Endpoint.yml
- include: Install_Package.yml
- include: Setting_Config.yml
- include: Create_Link.yml
- include: Initialize_Neutron.yml
- include: Services_Neutron.yml

