---
- name: Create_Database(check_database)
  shell: mysql -uroot -p{{ openstack_keystone_install.mariadb_pass }} -e "show databases;" | grep keystone
  register: ret_check_database
  changed_when: false
  failed_when: false

- name: Create_Database(create_database)
  shell: mysql -uroot -p{{ openstack_keystone_install.mariadb_pass }} -e "CREATE DATABASE keystone;"
  when: ret_check_database.rc != 0

- name: Create_Database(check_grant01)
  shell: mysql -uroot -p{{ openstack_keystone_install.mariadb_pass }} -e "show grants for 'keystone'@'localhost'" | grep "ALL PRIVILEGES ON \`keystone\`\.\* TO 'keystone'@'localhost'"
  register: ret_check_grant01
  changed_when: false
  failed_when: false

- name: Create_Database(grant01)
  shell: mysql -uroot -p{{ openstack_keystone_install.mariadb_pass }} -e "GRANT ALL PRIVILEGES ON keystone.* TO 'keystone'@'localhost' IDENTIFIED BY '{{ openstack_keystone_install.keystone_dbpass }}';"
  when: ret_check_grant01.rc != 0

- name: Create_Database(check_grant02)
  shell: mysql -uroot -p{{ openstack_keystone_install.mariadb_pass }} -e "show grants for 'keystone'@'%'" | grep "ALL PRIVILEGES ON \`keystone\`\.\* TO 'keystone'@'%'"
  register: ret_check_grant02
  changed_when: false
  failed_when: false

- name: Create_Database(grant02)
  shell: mysql -uroot -p{{ openstack_keystone_install.mariadb_pass }} -e "GRANT ALL PRIVILEGES ON keystone.* TO 'keystone'@'%' IDENTIFIED BY '{{ openstack_keystone_install.keystone_dbpass }}';"
  when: ret_check_grant02.rc != 0

