---
- name: create container
  docker_container:
    name: "{{ item.name }}"
    image: "{{ item.image }}"
    command: "{{ item.command }}"
    exposed_ports:
      "{{ item.exposed_ports | default(None)}}"
    network_mode: "{{ item.network_mode | default(\"bridge\")}}"
    state: "{{ item.state }}"
    tty: "{{ item.tty | default(\"no\") }}"
    interactive: "{{ item.interactive | default(\"no\") }}"
    detach: "{{ item.detach | default(\"no\")}}"
  when: item.state != absent
  with_items:
    "{{ docker_container_containers }}"

---
- name: delete container
  docker_container:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  when: item.state == absent
  with_items:
    "{{ docker_container_containers }}"
