---
- name: install package
  yum:
    name: docker
    state: installed

- name: set listen address and certificate dir
  template:
    src: docker.j2
    dest: /etc/sysconfig/docker
  notify: service restart

- name: service enable and start
  service:
    name: docker
    state: running
    enabled: yes

