---
- name: install epel-release
  yum:
    name: epel-release
    state: installed

- name: install package
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - docker
    - python-pip

- name: install docker-py
  pip:
    name: docker-py
    state: present

- name: set listen address and certificate dir
  template:
    src: docker.j2
    dest: /etc/sysconfig/docker
  notify: service restart

- name: service enable and start
  service:
    name: docker
    state: running
    enabled: yes

