---
- name: Setting_Config(DEFAULT)
  blockinfile:
    dest: /etc/nova/nova.conf
    insertafter: "^\\[DEFAULT"
    marker: "# {mark} ANSIBLE MANAGED BLOCK (openstack_nova_controller DEFAULT)"
    block: |
      enabled_apis = osapi_compute,metadata
      rpc_backend = rabbit
      auth_strategy = keystone
      my_ip = {{ openstack_nova_controller.mgmt_ip }}
      use_neutron = True
      firewall_driver = nova.virt.firewall.NoopFirewallDriver
    state: present

- name: Setting_Config(api_database)
  lineinfile:
    dest: /etc/nova/nova.conf
    insertafter: "^\\[api_database"
    line: connection = mysql+pymysql://nova:{{ openstack_nova_controller.nova_dbpass }}@{{ openstack_nova_controller.controller }}/nova_api
    state: present

- name: Setting_Config(database)
  lineinfile:
    dest: /etc/nova/nova.conf
    insertafter: "^\\[database"
    line: connection = mysql+pymysql://nova:{{ openstack_nova_controller.nova_dbpass }}@{{ openstack_nova_controller.controller }}/nova
    state: present

- name: Setting_Config(oslo_messaging_rabbit)
  blockinfile:
    dest: /etc/nova/nova.conf
    insertafter: "^\\[oslo_messaging_rabbit"
    marker: "# {mark} ANSIBLE MANAGED BLOCK (openstack_nova_controller oslo_messaging_rabbit)"
    block: |
      rabbit_host = {{ openstack_nova_controller.controller }}
      rabbit_userid = openstack
      rabbit_password = {{ openstack_nova_controller.rabbitmq_pass }}
    state: present

- name: Setting_Config(keystone_authtoken])
  blockinfile:
    dest: /etc/nova/nova.conf
    insertafter: "^\\[keystone_authtoken"
    marker: "# {mark} ANSIBLE MANAGED BLOCK (openstack_nova_controller keystone_authtoken)"
    block: |
      auth_uri = http://{{ openstack_nova_controller.controller }}:5000
      auth_url = http://{{ openstack_nova_controller.controller }}:35357
      memcached_servers = {{ openstack_nova_controller.controller }}:11211
      auth_type = password
      project_domain_name = default
      user_domain_name = default
      project_name = service
      username = nova
      password = {{ openstack_nova_controller.nova_pass }}
    state: present

- name: Setting_Config(vnc)
  blockinfile:
    dest: /etc/nova/nova.conf
    insertafter: "^\\[vnc"
    marker: "# {mark} ANSIBLE MANAGED BLOCK (openstack_nova_controller vnc)"
    block: |
      vncserver_listen = $my_ip
      vncserver_proxyclient_address = $my_ip
    state: present

- name: Setting_Config(glance)
  lineinfile:
    dest: /etc/nova/nova.conf
    insertafter: "^\\[glance"
    line: api_servers = http://{{ openstack_nova_controller.controller }}:9292
    state: present

- name: Setting_Config(oslo_concurrency)
  lineinfile:
    dest: /etc/nova/nova.conf
    insertafter: "^\\[oslo_concurrency"
    line: lock_path = /var/lib/nova/tmp
    state: present

