---
- hosts: all
  become: yes
  tasks:
    - name: Yum_Upgrade
      yum: >
        name=*
        state=latest
      notify:
        - reboot(reboot)
#        - reboot(wait_ssh_port_down)
        - reboot(wait_ssh_port_up)
  handlers:
    - name: reboot(reboot)
      shell: shutdown -r
      changed_when: true
      failed_when: false
    
    #- name: reboot(wait_ssh_port_down)
    #  wait_for: >
    #    host={{ inventory_hostname }}
    #    port={{ ansible_ssh_port }}
    #    state=stopped
    #  delegate_to: 127.0.0.1
    
    - name: reboot(wait_ssh_port_up)
      wait_for: >
        host={{ inventory_hostname }}
        port={{ ansible_ssh_port }}
        state=started
        delay=120
      delegate_to: 127.0.0.1
