---
- name: Create_Endpoint(check01)
  shell: . {{ openstack_glance.script_dir }}/admin-openrc && openstack endpoint list | grep glance | grep public
  register: ret_check01
  failed_when: false
  changed_when: false

- name: Create_Endpoint(create01)
  shell: . {{ openstack_glance.script_dir }}/admin-openrc && openstack endpoint create --region {{ openstack_glance.region }} image public http://{{ openstack_glance.controller }}:9292
  when: ret_check01.rc != 0

- name: Create_Endpoint(check02)
  shell: . {{ openstack_glance.script_dir }}/admin-openrc && openstack endpoint list | grep glance | grep internal
  register: ret_check02
  failed_when: false
  changed_when: false

- name: Create_Endpoint(create02)
  shell: . {{ openstack_glance.script_dir }}/admin-openrc && openstack endpoint create --region {{ openstack_glance.region }} image internal http://{{ openstack_glance.controller }}:9292
  when: ret_check02.rc != 0

- name: Create_Endpoint(check03)
  shell: . {{ openstack_glance.script_dir }}/admin-openrc && openstack endpoint list | grep glance | grep admin
  register: ret_check03
  failed_when: false
  changed_when: false

- name: Create_Endpoint(create03)
  shell: . {{ openstack_glance.script_dir }}/admin-openrc &&  openstack endpoint create --region {{ openstack_glance.region }} image admin http://{{ openstack_glance.controller }}:9292
  when: ret_check03.rc != 0

