---
- name: Create_User(check_exist)
  shell: . {{ openstack_glance.script_dir }}/admin-openrc && openstack user show glance
  failed_when: false
  changed_when: false
  register: ret_check_exist

- name: Create_User(create_user)
  shell: . {{ openstack_glance.script_dir }}/admin-openrc && openstack user create --domain {{ openstack_glance.domain }} --password {{ openstack_glance.glance_pass }} glance
  when: ret_check_exist.rc != 0

- name: Create_User(check_role)
  shell: . {{ openstack_glance.script_dir }}/admin-openrc && openstack role list --user glance --project service | grep admin
  changed_when: false
  failed_when: false
  register: ret_check_role

- name: Add_Role_Admin_User(create)
  shell: . {{ openstack_glance.script_dir }}/admin-openrc && openstack role add --project service --user glance admin
  when: ret_check_role.rc != 0

