---
- name: Create_Database(check_database)
  shell: mysql -uroot -p{{ openstack_glance.mariadb_pass }} -e "show databases;" | grep glance
  register: ret_check_database
  changed_when: false
  failed_when: false

- name: Create_Database(create_database)
  shell: mysql -uroot -p{{ openstack_glance.mariadb_pass }} -e "CREATE DATABASE glance;"
  when: ret_check_database.rc != 0

- name: Create_Database(check_grant01)
  shell: mysql -uroot -p{{ openstack_glance.mariadb_pass }} -e "show grants for 'glance'@'localhost'" | grep "ALL PRIVILEGES ON \`glance\`\.\* TO 'glance'@'localhost'"
  register: ret_check_grant01
  changed_when: false
  failed_when: false

- name: Create_Database(grant01)
  shell: mysql -uroot -p{{ openstack_glance.mariadb_pass }} -e "GRANT ALL PRIVILEGES ON glance.* TO 'glance'@'localhost' IDENTIFIED BY '{{ openstack_glance.glance_dbpass }}';"
  when: ret_check_grant01.rc != 0

- name: Create_Database(check_grant02)
  shell: mysql -uroot -p{{ openstack_glance.mariadb_pass }} -e "show grants for 'glance'@'%'" | grep "ALL PRIVILEGES ON \`glance\`\.\* TO 'glance'@'%'"
  register: ret_check_grant02
  changed_when: false
  failed_when: false

- name: Create_Database(grant02)
  shell: mysql -uroot -p{{ openstack_glance.mariadb_pass }} -e "GRANT ALL PRIVILEGES ON glance.* TO 'glance'@'%' IDENTIFIED BY '{{ openstack_glance.glance_dbpass }}';"
  when: ret_check_grant02.rc != 0

