---
- name: Setting_Config(api01)
  lineinfile: >
    dest=/etc/glance/glance-api.conf
    insertafter="^\[database"
    line="connection = mysql+pymysql://glance:{{ openstack_glance.glance_dbpass }}@{{ openstack_glance.controller }}/glance"
    state=present

- name: Setting_Config(api02)
  blockinfile:
    dest: /etc/glance/glance-api.conf
    insertafter: "^\\[keystone_authtoken"
    block: |
      auth_uri = http://{{ openstack_glance.controller }}:5000
      auth_url = http://{{ openstack_glance.controller }}:35357
      memcached_servers = {{ openstack_glance.controller }}:11211
      auth_type = password
      project_domain_name = default
      user_domain_name = default
      project_name = service
      username = glance
      password = {{ openstack_glance.glance_pass }}
    state: present

- name: Setting_Config(api03)
  lineinfile: >
    dest=/etc/glance/glance-api.conf
    insertafter="^\[paste_deploy"
    line="flavor = keystone"
    state=present

